services:
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.1.1
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    depends_on:
      - mysql
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - evolution-net

  mysql:
    container_name: mysql
    image: percona/percona-server:8.0
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=evolution
      - TZ=America/Bahia
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - evolution-net

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - evolution-net

volumes:
  evolution_instances:
  mysql_data:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge
